spring:
  application:
    name: order-stock-movement-service
  datasource:
    url: jdbc:postgresql://postgres-service:5432/simple_orders
    username: simple
    password: S1mpl30rd3r5P4ss
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8085'
  servlet:
    context-path: /order-stock-movement-service

logging:
  level:
    org.springframework: ERROR
    com.franzoia: DEBUG
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: orderstockmovement-service.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"

eureka:
  client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

